### config.toml --- 
## 
## Filename: config.toml
## Author: Louise <louise>
## Created: Tue Dec 26 23:31:49 2017 (+0100)
## Last-Updated: Tue Dec 26 23:56:29 2017 (+0100)
##           By: Louise <louise>
######################################################################

[video]
scale = 2

[audio]
sample-rate = 48000

[input]
A = "Q"
B = "W"
Start = "Return"
Select = "Space"
Up = "Up"
Down = "Down"
Left = "Left"
Right = "Right"